//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.04 at 11:10:49 AM EST 
//


package org.oasis.saml2.metadata;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.oasis.saml2.metadata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SingleLogoutService_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "SingleLogoutService");
    private final static QName _AttributeService_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "AttributeService");
    private final static QName _AuthzService_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "AuthzService");
    private final static QName _AuthnQueryService_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "AuthnQueryService");
    private final static QName _ManageNameIDService_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "ManageNameIDService");
    private final static QName _AffiliateMember_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "AffiliateMember");
    private final static QName _GivenName_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "GivenName");
    private final static QName _SurName_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "SurName");
    private final static QName _ServiceName_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "ServiceName");
    private final static QName _RoleDescriptor_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "RoleDescriptor");
    private final static QName _Company_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "Company");
    private final static QName _OrganizationDisplayName_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "OrganizationDisplayName");
    private final static QName _ServiceDescription_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "ServiceDescription");
    private final static QName _OrganizationName_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "OrganizationName");
    private final static QName _NameIDFormat_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "NameIDFormat");
    private final static QName _NameIDMappingService_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "NameIDMappingService");
    private final static QName _ArtifactResolutionService_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "ArtifactResolutionService");
    private final static QName _AssertionConsumerService_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "AssertionConsumerService");
    private final static QName _SingleSignOnService_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "SingleSignOnService");
    private final static QName _AttributeProfile_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "AttributeProfile");
    private final static QName _EmailAddress_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "EmailAddress");
    private final static QName _TelephoneNumber_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "TelephoneNumber");
    private final static QName _AssertionIDRequestService_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:metadata", "AssertionIDRequestService");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.oasis.saml2.metadata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SPSSODescriptor }
     * 
     */
    public SPSSODescriptor createSPSSODescriptor() {
        return new SPSSODescriptor();
    }

    /**
     * Create an instance of {@link KeyDescriptor }
     * 
     */
    public KeyDescriptor createKeyDescriptor() {
        return new KeyDescriptor();
    }

    /**
     * Create an instance of {@link OrganizationURL }
     * 
     */
    public OrganizationURL createOrganizationURL() {
        return new OrganizationURL();
    }

    /**
     * Create an instance of {@link AdditionalMetadataLocation }
     * 
     */
    public AdditionalMetadataLocation createAdditionalMetadataLocation() {
        return new AdditionalMetadataLocation();
    }

    /**
     * Create an instance of {@link AttributeConsumingService }
     * 
     */
    public AttributeConsumingService createAttributeConsumingService() {
        return new AttributeConsumingService();
    }

    /**
     * Create an instance of {@link EndpointType }
     * 
     */
    public EndpointType createEndpointType() {
        return new EndpointType();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link RequestedAttribute }
     * 
     */
    public RequestedAttribute createRequestedAttribute() {
        return new RequestedAttribute();
    }

    /**
     * Create an instance of {@link PDPDescriptor }
     * 
     */
    public PDPDescriptor createPDPDescriptor() {
        return new PDPDescriptor();
    }

    /**
     * Create an instance of {@link EntityDescriptor }
     * 
     */
    public EntityDescriptor createEntityDescriptor() {
        return new EntityDescriptor();
    }

    /**
     * Create an instance of {@link AttributeAuthorityDescriptor }
     * 
     */
    public AttributeAuthorityDescriptor createAttributeAuthorityDescriptor() {
        return new AttributeAuthorityDescriptor();
    }

    /**
     * Create an instance of {@link Extensions }
     * 
     */
    public Extensions createExtensions() {
        return new Extensions();
    }

    /**
     * Create an instance of {@link AffiliationDescriptor }
     * 
     */
    public AffiliationDescriptor createAffiliationDescriptor() {
        return new AffiliationDescriptor();
    }

    /**
     * Create an instance of {@link IndexedEndpointType }
     * 
     */
    public IndexedEndpointType createIndexedEndpointType() {
        return new IndexedEndpointType();
    }

    /**
     * Create an instance of {@link ContactPerson }
     * 
     */
    public ContactPerson createContactPerson() {
        return new ContactPerson();
    }

    /**
     * Create an instance of {@link AuthnAuthorityDescriptor }
     * 
     */
    public AuthnAuthorityDescriptor createAuthnAuthorityDescriptor() {
        return new AuthnAuthorityDescriptor();
    }

    /**
     * Create an instance of {@link LocalizedNameType }
     * 
     */
    public LocalizedNameType createLocalizedNameType() {
        return new LocalizedNameType();
    }

    /**
     * Create an instance of {@link IDPSSODescriptor }
     * 
     */
    public IDPSSODescriptor createIDPSSODescriptor() {
        return new IDPSSODescriptor();
    }

    /**
     * Create an instance of {@link EntitiesDescriptor }
     * 
     */
    public EntitiesDescriptor createEntitiesDescriptor() {
        return new EntitiesDescriptor();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndpointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "SingleLogoutService")
    public JAXBElement<EndpointType> createSingleLogoutService(EndpointType value) {
        return new JAXBElement<EndpointType>(_SingleLogoutService_QNAME, EndpointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndpointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "AttributeService")
    public JAXBElement<EndpointType> createAttributeService(EndpointType value) {
        return new JAXBElement<EndpointType>(_AttributeService_QNAME, EndpointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndpointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "AuthzService")
    public JAXBElement<EndpointType> createAuthzService(EndpointType value) {
        return new JAXBElement<EndpointType>(_AuthzService_QNAME, EndpointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndpointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "AuthnQueryService")
    public JAXBElement<EndpointType> createAuthnQueryService(EndpointType value) {
        return new JAXBElement<EndpointType>(_AuthnQueryService_QNAME, EndpointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndpointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "ManageNameIDService")
    public JAXBElement<EndpointType> createManageNameIDService(EndpointType value) {
        return new JAXBElement<EndpointType>(_ManageNameIDService_QNAME, EndpointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "AffiliateMember")
    public JAXBElement<String> createAffiliateMember(String value) {
        return new JAXBElement<String>(_AffiliateMember_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "GivenName")
    public JAXBElement<String> createGivenName(String value) {
        return new JAXBElement<String>(_GivenName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "SurName")
    public JAXBElement<String> createSurName(String value) {
        return new JAXBElement<String>(_SurName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocalizedNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "ServiceName")
    public JAXBElement<LocalizedNameType> createServiceName(LocalizedNameType value) {
        return new JAXBElement<LocalizedNameType>(_ServiceName_QNAME, LocalizedNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoleDescriptorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "RoleDescriptor")
    public JAXBElement<RoleDescriptorType> createRoleDescriptor(RoleDescriptorType value) {
        return new JAXBElement<RoleDescriptorType>(_RoleDescriptor_QNAME, RoleDescriptorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "Company")
    public JAXBElement<String> createCompany(String value) {
        return new JAXBElement<String>(_Company_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocalizedNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "OrganizationDisplayName")
    public JAXBElement<LocalizedNameType> createOrganizationDisplayName(LocalizedNameType value) {
        return new JAXBElement<LocalizedNameType>(_OrganizationDisplayName_QNAME, LocalizedNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocalizedNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "ServiceDescription")
    public JAXBElement<LocalizedNameType> createServiceDescription(LocalizedNameType value) {
        return new JAXBElement<LocalizedNameType>(_ServiceDescription_QNAME, LocalizedNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocalizedNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "OrganizationName")
    public JAXBElement<LocalizedNameType> createOrganizationName(LocalizedNameType value) {
        return new JAXBElement<LocalizedNameType>(_OrganizationName_QNAME, LocalizedNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "NameIDFormat")
    public JAXBElement<String> createNameIDFormat(String value) {
        return new JAXBElement<String>(_NameIDFormat_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndpointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "NameIDMappingService")
    public JAXBElement<EndpointType> createNameIDMappingService(EndpointType value) {
        return new JAXBElement<EndpointType>(_NameIDMappingService_QNAME, EndpointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndexedEndpointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "ArtifactResolutionService")
    public JAXBElement<IndexedEndpointType> createArtifactResolutionService(IndexedEndpointType value) {
        return new JAXBElement<IndexedEndpointType>(_ArtifactResolutionService_QNAME, IndexedEndpointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndexedEndpointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "AssertionConsumerService")
    public JAXBElement<IndexedEndpointType> createAssertionConsumerService(IndexedEndpointType value) {
        return new JAXBElement<IndexedEndpointType>(_AssertionConsumerService_QNAME, IndexedEndpointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndpointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "SingleSignOnService")
    public JAXBElement<EndpointType> createSingleSignOnService(EndpointType value) {
        return new JAXBElement<EndpointType>(_SingleSignOnService_QNAME, EndpointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "AttributeProfile")
    public JAXBElement<String> createAttributeProfile(String value) {
        return new JAXBElement<String>(_AttributeProfile_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "EmailAddress")
    public JAXBElement<String> createEmailAddress(String value) {
        return new JAXBElement<String>(_EmailAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "TelephoneNumber")
    public JAXBElement<String> createTelephoneNumber(String value) {
        return new JAXBElement<String>(_TelephoneNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndpointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:metadata", name = "AssertionIDRequestService")
    public JAXBElement<EndpointType> createAssertionIDRequestService(EndpointType value) {
        return new JAXBElement<EndpointType>(_AssertionIDRequestService_QNAME, EndpointType.class, null, value);
    }

}
